name: Linux CI

on:
  push:
    branches: [ trunk ]
    paths:
    - '**'
    - '!**/codeql.yml'
  pull_request:
    branches: [ trunk ]
    paths:
    - '**'
    - '!**/codeql.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        name: [default]
        os: [ubuntu-22.04, ubuntu-24.04]
        cxx: [g++, clang++]
    runs-on: ${{ matrix.os }}
    env:
      CXX: ${{ matrix.cxx }}

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: make -j$(nproc)

      - name: Check
        run: make check

  meson:
    strategy:
      fail-fast: false
      matrix:
        name: [default]
        os: [ubuntu-22.04, ubuntu-24.04]
        cxx: [g++, clang++]
    runs-on: ${{ matrix.os }}
    env:
      CXX: ${{ matrix.cxx }}
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update && sudo apt upgrade -y
          sudo apt install -y --no-install-recommends meson

      - name: Build
        run: |
          meson setup _build
          meson compile -C _build
