name: Linux CI
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches: [ trunk ]
    paths:
    - '**'
    - '!**.yml'
    - '**/linux.yml'
  pull_request:
    branches: [ trunk ]
    paths:
    - '**'
    - '!**.yml'
    - '**/linux.yml'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        name: [default]
        os: [ubuntu-22.04, ubuntu-24.04]
        cxx: [g++, clang++]
    runs-on: ${{ matrix.os }}
    env:
      CXX: ${{ matrix.cxx }}
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update && sudo apt upgrade -y
          sudo apt install -y --no-install-recommends meson

      - name: Build
        run: |
          meson setup _build -Dbuild_all=true
          meson compile -C _build

      - name: Test
        run: |
          meson test -C _build
