name: Linux CI

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        name: [default]
        os: [ubuntu-22.04, ubuntu-24.04]
        cxx: [g++, clang++]
    runs-on: ubuntu-latest
    env:
      CXX: ${{ matrix.cxx }}

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: make -j$(nproc)

      - name: Check
        run: make check
